services:
  - type: web
    name: cryptobull-p2p
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
